language: go

go:
  - "1.24.x"
  - "1.23.x" 
  - "1.22.x"
  - "1.21.x"

env:
  - GO111MODULE=on

# 在运行测试前执行的命令
before_script:
  - go mod download
  - go mod verify

# 执行的测试命令
script:
  - go test -v -race -coverprofile=coverage.out ./...
  - go vet ./...
  - go fmt -l . | grep -v "^$" && exit 1 || true

# 测试成功后执行的命令
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.out

# 缓存模块以加速构建
cache:
  directories:
    - $GOPATH/pkg/mod

# 通知设置（可选）
notifications:
  email: false
